#!/usr/bin/env python
#coding:utf-8
import csv, datetime, os, sys

def gen_lang_file(lang):
    csv_filename = 'lang.csv'
    lang_file_name = '%s_Localizable.strings'%(lang)
    count = 0
    with open(lang_file_name, 'wb') as lang_file, open(csv_filename, 'rb') as csv_file:
        reader = csv.DictReader(csv_file, delimiter=',', quotechar='\"')
        lang_file.write("/*\n")
        lang_file.write("Localizable.strings\n")
        date = datetime.datetime.now().strftime('%m/%d/%Y')  
        this_file = os.path.split(sys.argv[0])[-1]
        lang_file.write("This file is automatically generated by %s on %s. Do not modify!\n"%(this_file, date))
        lang_file.write("Copyright © 2016 Spotlite. All rights reserved.\n")
        lang_file.write("*/\n")
        keys = {}        
        for row in reader:
            module = row['Module'].strip()
            function = row['Function'].strip()
            tag = row['Tag'].strip()
            if (len(module) == 0 or len(function) == 0):
                print '\033[1;33mwarning: line %d, empty module or function\033[0m'%(reader.line_num)
                continue
            key = module + '_' + function
            if len(tag) > 0:
                key += '_' + tag
            if key in keys:
                print '\033[1;31merror: line %d, duplicated key "%s"\033[0m'%(reader.line_num, key)
                exit(255) 
            keys[key] = key
            value = row[lang]
            lang_file.write('%s = \"%s\";\n'%(key, value))
            count = count + 1
    print 'done %s, %d pairs written'%(lang_file_name, count)      

gen_lang_file('en')
gen_lang_file('zh-Hans')
